<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Fields</name>
   <tag></tag>
   <elementGuidId>2eedc389-2ef4-49f9-b555-081cbde648e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.caption > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='field-summary']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Fields&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10a32069-7c7c-479a-ada6-c6b78733474b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fields</value>
      <webElementGuid>0e6a5b8d-90e0-44dc-b5fb-91a60558787b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-summary&quot;)/div[@class=&quot;caption&quot;]/span[1]</value>
      <webElementGuid>4c7fdd51-6092-44ee-878c-0814f30cfda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='field-summary']/div/span</value>
      <webElementGuid>79a5647a-9a3f-451b-8d03-7a3efb18bfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field Summary'])[1]/following::span[1]</value>
      <webElementGuid>83c07c14-be71-4108-8d2b-1398f4c207e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object'])[1]/following::span[1]</value>
      <webElementGuid>ad3b2ad9-7fe0-45f3-a5cd-a67b0dba2a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modifier and Type'])[1]/preceding::span[1]</value>
      <webElementGuid>43538041-9a46-4497-9c9c-b1a0f7831b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Field'])[3]/preceding::span[1]</value>
      <webElementGuid>4f626ad5-c263-4bfc-9931-47e41dcfaf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fields']/parent::*</value>
      <webElementGuid>593b4f6e-e922-47b7-8189-71745770724c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/section/div/span</value>
      <webElementGuid>0577668c-79c3-436e-96ec-6182f050a6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Fields' or . = 'Fields')]</value>
      <webElementGuid>f38f7cca-2d76-43c0-a860-20b4d1952c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
